### ISSUE TITLE
what do I do ? 

### ISSUE THREAD

**Issue by PooveyCentral** [KylinWu/StrawpollVoteBot#12]
Hi, This is what is happening could you please help,btw I am using the latest version of Ubuntu and any plugin.
![screenshot_1](https://cloud.githubusercontent.com/assets/16356440/11912191/50dc7596-a62a-11e5-8408-3fb57b19ebd6.png)

Thanks in advance

**Comment by innovativemilk** [comment]
Dont use a virtual machine

**Comment by innovativemilk** [comment]
Install php5 and curl

**Comment by PooveyCentral** [comment]
i have done that

**Comment by PooveyCentral** [comment]
should i try to update them again ?

**Comment by PooveyCentral** [comment]
soo do you think if i just run ubuntu of a usb and try it there it should
work ?

**Comment by kulits** [comment]
Here's a hint: Navigate to the folder with the file that you want to open.
