### ISSUE TITLE
How do I start it

### ISSUE THREAD

**Issue by Pokejongen** [KylinWu/StrawpollVoteBot#3]
Hi, can you maybe send me a detailed description on how to start it, this pops up with me:
Notice: Undefined variable: argc in C:\xampp\htdocs\votebot\vote.php on line 5 Usage: php vote.php
I hope you can help. Friendly greetings Pokejongen

**Comment by Demonly** [comment]
Are you running this off your main computer? If you are. This is built for something that has PHP on it like a dedicated server or a VPS. Whenever you have that, just browse to the location of the files and type the following statements into your command line:
- php update_proxies.php
- php vote.php [ID OF STRAWPOLL] [OPTION] 1000
