### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by PokeThat** [KylinWu/StrawpollVoteBot#5]
Hi I am trying to use the votebot but its not working i can update the proxies fine but when i want to use it it says:
Object not found!

The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

Can you please tell me what to do?
Thank you -Poke

**Comment by dragonbane** [comment]
Hey @PokeThat.  I just downloaded this today and no issues.  Proxies updated and successfully voted 800 times on a poll.  It took a few goes for all of those votes to go through but it worked.

I ran this on an Ubuntu machine.  Basically Laravel Homestead.

What was the command line you were entering?

**Comment by PokeThat** [comment]
Hi Thanks @dragonbane  for helping The Command i Used was
vote.php 5567481 2 100

Hope you can help me 
I Also updated the Proxies Fine

Is theres something wrong with my server I am using XAMPP If there is Can you please tell me or what do i have to do 
Thanks.-Poke

**Comment by dragonbane** [comment]
@PokeThat, you need to run:
**php** vote.php 5567481 2 100

This will run it through the PHP interpreter via the command line.

In XAMPP, you may also need to enable the cURL extension.
