### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SaroxDE** [KylinWu/StrawpollVoteBot#6]
Hey,
I get this Error:
PHP Fatal error:  Call to undefined function curl_multi_init() in /var/www/inc/class.Strawpoll.php on line 8

**Comment by lewisgibson** [comment]
How do you even use it?? Please help D;

**Comment by KylinWu** [comment]
@SaroxDE 
http://stackoverflow.com/questions/4396779/fatal-error-call-to-undefined-function-curl-init-in-on-line-9
