### ISSUE TITLE
Bot stops working, when choosing a high amount of votes

### ISSUE THREAD

**Issue by ByteRaper** [KylinWu/StrawpollVoteBot#7]
Hey Kylin,
why isnt the bot working, if you choose a high amount of proxy entries?
I upped the amount check by hand to 5000, and at approximately 3000 votes, the bot stops working and does nothing, although there are enough proxies available.

**Comment by treyshaffer** [comment]
This is resulting because of: `if($amount > 1000) {
            $amount = count($proxies);      
    }`, which is basically just making sure that it does not use more proxies than exist within the file. If it is at 3000 for you, then that must mean that there are 3000 proxies available in the file.

**Comment by ByteRaper** [comment]
There are more  proxies available in the file.
